name: Fetch OIDC Token

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  fetch-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Request OIDC Token
        id: oidc
        uses: actions/github-script@v7
        with:
          script: |
            const token = await core.getIDToken('api://AzureADTokenExchange');
            core.setOutput('id_token', token);

      - name: Decode and print token
        run: |
          echo "Saving token..."
          TOKEN="${{ steps.oidc.outputs.id_token }}"
          echo "::add-mask::$TOKEN"
          echo "$TOKEN" > token.txt

          echo "----- TOKEN PAYLOAD -----"
          echo "$TOKEN" | cut -d '.' -f2 | base64 -d 2>/dev/null || echo "Decode error"
